### ISSUE TITLE
Inconsistent speed durring deplacement

### ISSUE THREAD

**Issue by coookiecoder** [pupitoe/cube_3d#40]
# forward or backward : 
- `sqrt(1 * 1 + 0 * 0)`
- `sqrt(1 + 0)`
- `sqrt(1)`
- `1 unit / fps`
# left or right :
- `sqrt(0 * 0 + 1 * 1)`
- `sqrt(0 + 1)`
- `sqrt(1)`
- `1 unit / fps`
# (forward or backward) AND (left or right) :
- `sqrt(1 * 1 + 1 * 1)`
- `sqrt(1 + 1)`
- `sqrt(2)`
- `1.41 unit / fps`
# rather than :
# (forward or backward) AND (left or right) :
- `sqrt(0.70 * 0.70 + 0.70 * 0.70)`
- `sqrt(0.5 + 0.5)`
- `sqrt(1)`
- `1 unit / fps`
# why 0.70 ?
- `1 * cos (45) = 0.707106781187`

**Comment by pupitoe** [comment]
i do not understand
